spring:
  jpa:
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:project;NON_KEYWORDS=USER;MODE=MySQL
  sql:
    init:
      schema-locations:
      data-locations: classpath:data.sql
    jpa:
  hibernate:
    ddl-auto: create
  properties:
    hibernate:
      format_sql: true
logging:
  level:
    org:
      springframework:
        jdbc:
          core: TRACE


